### ISSUE TITLE
Zoom and Pan feature for the charts in the victory-native-xl library

### ISSUE THREAD

**Issue by amitach** [FormidableLabs/victory-native-xl#154] opened 2023-10-25 11:33 UTC
### Description

I would like to request the addition of a Zoom and Pan feature for the charts in the victory-native-xl library. This feature would greatly enhance the user experience by allowing users to zoom into specific sections of the chart for a more detailed view and pan across to navigate the zoomed-in sections. This is especially useful for charts with a large amount of data or when users want to focus on specific data points or ranges.

Use Cases:

Analyzing detailed data points in large datasets.
Enhancing user interaction and engagement with the charts.
Providing a more comprehensive data visualization tool for users who need to delve deep into their data.
Benefits:

Improved user experience.
More flexibility in data visualization.
Aligns with features offered by other leading charting libraries.

### Proposal

I propose the following implementation steps for the Zoom and Pan feature:

Gesture Recognition: Integrate gesture recognition to detect pinch (for zoom) and drag (for pan) gestures on the chart.
Zoom Functionality: Allow users to zoom in and out by pinching on the chart. The zoom level should be adjustable, and there should be limits to prevent excessive zooming.
Pan Functionality: Once zoomed in, users should be able to drag the chart to navigate through the zoomed section. Panning should be smooth and intuitive.
Reset Option: Provide an option (like a button) to reset the chart to its original state/zoom level.
UI Feedback: When zoomed in, provide UI feedback, such as a zoom level indicator or a mini-map, to show users which part of the chart they are viewing.
### LInks
https://github.com/wuxudong/react-native-charts-wrapper
look for scaleEnabled property

**Comment by rarchitgupta** [comment] 2023-10-27 12:27
Also looking for the same solution, requesting those involved to consider and look into this

**Comment by agusvazquez** [comment] 2023-10-30 14:04
Hello! This is a duplicate of https://github.com/FormidableLabs/victory-native-xl/issues/143

**Comment by zibs** [comment] 2024-01-23 20:56
Thanks @agusvazquez  - let's track this there for now.

**Closed by zibs** 2024-01-23 20:56 UTC
